name: pos_rp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  audioplayers: ^6.0.0
  esc_pos_utils_plus: ^2.0.2
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  pdf: ^3.11.3
  permission_handler: ^11.3.1
  print_bluetooth_thermal: ^1.1.6
  provider: ^6.1.2
  screenshot: ^3.0.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sqflite: ^2.3.3+1
  uuid: ^4.4.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # Optional
  web:
    generate: true
  macos:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
